Rm confusing Request Payload description, point to prior docs for clarification
Cadasta/api-docs pull request #31
Opened 2017-05-16 16:56 UTC by alukach

The current docs regarding creating `SpatialUnit` instances seems to suggest that the GeoJSON data should be put behind the `geometry` key of the request payload. In actuality, our API expects that the request payload be the GeoJSON, with the additional `SpatialUnit` properties being placed in the `properties` property of the GeoJSON object.  This is as described in the "Spatial Unit JSON Object" section of the docs.  I think it's best to just point to that documentation rather than rewriting it in the "Creating Spatial Units" section.

2017-05-16 17:00 UTC, alukach commented
I guess this change fails to indicate that `properties.type` is required while `properties.attributes` is not.  Additionally, in practice, it appears that `properties.type` is not actually required.

2017-05-16 17:08 UTC, alukach commented
Actually, disregard that earlier idea.  PR updated, I think the following is better:

**Request Payload**

Request object should formatted as a <a href="https://en.wikipedia.org/wiki/GeoJSON" target="_blank"> GeoJSON object</a>), as described in the [Spatial Unit JSON Object documentation](##spatial-unit-json-object).

Property | Type | Required? | Description
--- | --- | :---: | ---
`geometry` | `Object` | x | A <a href="https://en.wikipedia.org/wiki/GeoJSON#Geometries" target="_blank"> GeoJSON Feature's geometry attribute</a>) defining the geographic coordinates of the location.
`properties.type` | `String` | x | This refers to the possible land `types` that the location could be (e.g. `PA` = Parcel). See the **Land `type` Abbreviations**  table above for more information.
`properties.attributes` | `Array` |  | An array of different attributes for the property.

2017-05-16 17:27 UTC, alukach commented
Hmmm... Continuing with this, there are some weird behaviours with this endpoint. I'm not sure which we should record in the docs and which we should ignore.

For example, if you don't include a `properties` attribute on the GeoJSON payload, our system tries to use the `type` from the payload.  For example, this is a valid payload:

```python
In [78]: geom
Out[78]:
{'geometry': {'coordinates': [96.534042, 18.774717], 'type': 'Point'},
 'type': 'PA'}

In [79]: cnxn.post(endpoints.locations('data-import-org', 'mutraw-district'), json=geom).
    ...: json()
Out[79]:
{u'geometry': {u'coordinates': [96.534042, 18.774717], u'type': u'Point'},
 u'properties': {u'attributes': {},
  u'id': u'4ac34v2wa4tpuw6tzb67nw49',
  u'type': u'PA'},
 u'type': u'Feature'}
```

This actually fits in with what the docs said before this PR.

However, if you include a properties attribute, it will pull the `type` out of that:

```python
In [75]: geom
Out[75]:
{'geometry': {'coordinates': [96.534042, 18.774717], 'type': 'Point'},
 'properties': {'type': 'MI'},
 'type': 'PA'}

In [76]: cnxn.post(endpoints.locations('data-import-org', 'mutraw-district'), json=geom).
    ...: json()
Out[76]:
{u'geometry': {u'coordinates': [96.534042, 18.774717], u'type': u'Point'},
 u'properties': {u'attributes': {},
  u'id': u'qpnc8aqt7uq462bqkgksznip',
  u'type': u'MI'},
 u'type': u'Feature'}
```

So basically you have two options:

### 1. POST a Payload as described in docs currently

Request body should NOT be GeoJSON, rather it's just a JSON payload:

Property | Type | Required? | Description
--- | --- | :---: | ---
`geometry` | `Object` | x | A <a href="https://en.wikipedia.org/wiki/GeoJSON#Geometries" target="_blank"> GeoJSON Feature's geometry attribute</a>)defining the geographic coordinates of the location.
`type` | `String` | x | This refers to the possible land `types` that the location could be (e.g. `PA` = Parcel). See the **Land `type` Abbreviations**  table above for more information.
`attributes` | `Array` |  | An array of different attributes for the property.


### 2. POST a GeoJSON Payload

Property | Type | Required? | Description
--- | --- | :---: | ---
`type` | `String` |  | This will be ignored. All GeoJSON features will be of type `Feature`.
`geometry` | `Object` | x | A <a href="https://en.wikipedia.org/wiki/GeoJSON#Geometries" target="_blank"> GeoJSON Feature's geometry attribute</a>defining the geographic coordinates of the location.
`properties` | `Object` | x | Object to store meta attributes about the Spatial Unit.
`properties.type` | `String` | x | This refers to the possible land `types` that the location could be (e.g. `PA` = Parcel). See the **Land `type` Abbreviations**  table above for more information.
`properties.attributes` | `Array` |  | An array of different attributes for the property.


Should our docs reflect both options?  Additionally, is the description for `attributes`/`properties.attributes` correct?  Should the input be an `Array`? That doesn't seem right to me.  Should it be instead changed to the description of `attributes` described in the "Spatial Unit JSON Object" section?

Property | Type | Description
---|---|---
`attributes` | `Object` | Project-specific attributes that are defined through the projects questionnaire.

2017-05-17 15:55 UTC, oliverroick requested changes
My initial thought was that is should always be GeoJSON. In that case, we should make sure we only accept a valid GeoJSON object, which would require us to implement custom validation. Either we do that (which I can't assess how much work that actually is) or we should add both cases to the docs to clarify that you can post both. It's obviously somewhat confusing.

2017-05-17 15:55 UTC, oliverroick commented on content/06-records.md
> +`properties.attributes` | `Array` |  | An array of different attributes for the property.
`properties.attributes` should be an object.

2017-05-17 15:55 UTC, oliverroick commented on content/06-records.md
> +`geometry` | `Object` | x | A <a href="https://en.wikipedia.org/wiki/GeoJSON#Geometries" target="_blank"> GeoJSON Feature's geometry attribute</a>)defining the geographic coordinates of the location.
There's a stray `)` in the description column. (Not your fault but while you're at it)

2018-03-14 15:44 UTC, alukach commented
While I do believe this is still valid, it is not of priority as we will likely be moving away from this API. Closing for now.

2018-03-14 15:44 UTC, closed without merging