Auto update gh-pages branch when docs are updated.
Cadasta/api-docs pull request #44
Opened 2017-10-19 23:09 UTC by m-murad

This PR is relate to #40 
This will auto update `gh-pages` branch when `master` branch is updated.

@oliverroick please review.

2017-10-19 23:10 UTC, m-murad commented
Travis needs to be enabled for the project and an API key needs to be added in the travis console.

2017-10-19 23:29 UTC, m-murad commented on deploy.sh
> +git clone --quiet --branch=gh-pages https://oliverroick:$API_KEY@github.com/cadasta/api-docs  /home/travis/build/cadasta/docs-branch
@oliverroick 
You need to generate an API key and use it in travis.
1. Read about generating an API key [here](https://github.com/blog/1509-personal-api-tokens).
2. Once you generate the API key open the project in travis-ci.org.
3. In settings tab add an environment variable. Name the variable `API_KEY` and value the key you generated.
![screen shot 2017-10-20 at 4 51 16 am](https://user-images.githubusercontent.com/17262180/31798625-60c3c480-b552-11e7-8ff7-d2fae70eceb2.png)

2017-10-26 10:48 UTC, oliverroick requested changes
Hi @m-murad, thanks for getting automated deploys started. That will make the process much easier for us. 

I left a few comments that I would like you to address. Once we have accepted your changes, I'll enable the project on Travis so we can see if the project is built correctly.

2017-10-26 10:48 UTC, oliverroick commented on deploy.sh
> +if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_REPO_SLUG" != "cadasta/api-docs" ]; then
This condition looks wrong. The first part excludes all builds on pull requests, the second part excludes all builds that are not triggered from `cadasta/api-docs`, which will never become `false`, since all builds will always be triggered from `cadasta/api-docs`. 

Connecting both with an `OR` operator (you're using `-o`) means the build will never exit. 

As I suggested in my [comment to the corresponding issue](https://github.com/Cadasta/api-docs/issues/40#issuecomment-339616590), I would use:

```bash
if ["$TRAVIS_TAG" != "false"]
```

That way we only ever deploy when a new version has been tagged.

2017-10-26 10:48 UTC, oliverroick commented on deploy.sh
> +git clone --quiet --branch=gh-pages https://oliverroick:$API_KEY@github.com/cadasta/api-docs  /home/travis/build/cadasta/docs-branch
I'll create a bot user for these tasks, that build won't break when a user is removed from the team.

2017-10-26 10:48 UTC, oliverroick commented on deploy.sh
> +git push origin gh-pages --quiet
For the time being, can we push this to another branch, maybe `gh-pages-test`? I want to see the script in action before we start overwriting docs website. 

Once your changes are approved, I'll change that back.

2017-10-26 10:48 UTC, oliverroick commented on deploy.sh
> -npm install
I'm not too familiar with building Node projects on Travis. I'm assuming that Travis always runs `npm install` by default?!

2017-10-26 10:48 UTC, oliverroick commented on deploy.sh
> +git commit -m "Deploy docs"
Is there a way to use the content of `$TRAVIS_TAG` here to get nicer commit messages? For example, if we tag `1.0.1` that we end up with the commit message `Deploy docs v1.0.1`.

2017-10-26 12:00 UTC, m-murad commented on deploy.sh
> -npm install
Yes it does

2017-10-26 12:37 UTC, m-murad commented on deploy.sh
> +if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_REPO_SLUG" != "cadasta/api-docs" ]; then
`"$TRAVIS_REPO_SLUG" != "cadasta/api-docs"`
This condition is for a scenario where commit or PR is made on the forked copy of this repository. 
e.g. if I'm making the changes on my own copy of the repository i.e. `m-murad/api-docs` the auto update will be skipped.

2017-10-26 12:40 UTC, m-murad commented on deploy.sh
> +git clone --quiet --branch=gh-pages https://oliverroick:$API_KEY@github.com/cadasta/api-docs  /home/travis/build/cadasta/docs-branch
Sure

2017-10-26 13:16 UTC, m-murad commented on deploy.sh
> +git commit -m "Deploy docs"
I'm still not able to understand what you are trying to say.

I checked this repository but no tag has been created for this repository. Maybe if you can explain it to me.

What we can do we can use the commit message of the commit that is being build or the branch of the pull request.

2017-10-26 14:35 UTC, oliverroick commented on deploy.sh
> +git commit -m "Deploy docs"
Yes, no tags have been created so far. But we will create tags in the future to kick off the deployment process. 

So whenever we think that what is on `master` is ready, we create a new tag, which deploys the docs. I don't want to deploy the docs with every push to master for a simple reason: When we build features for the API and document the changes, the changes to the documentation might be merged to master before the changes to the API are released. If we deploy with every push to master, the documentation won't match the current API and we can avoid that by tagging versions on master and deploy only when a new tag is created.

2017-10-26 14:39 UTC, m-murad commented on deploy.sh
> +git commit -m "Deploy docs"
For that we can do something else.

Once a TAG is created at `cadasta/cadasta-platform` i will right a script that will create the TAG in this repository as well. 

This way the docs will remain updated after every commit and when a new tag is created for `cadasta-platform` it will automatically create a tag for `api-docs`.

2017-10-26 14:40 UTC, m-murad commented on deploy.sh
> +git commit -m "Deploy docs"
I'm suggesting updating the docs after every commit because after my PRs #37, #39, #36 
The docs are still not updated to reflect the changes.

2017-10-26 14:42 UTC, m-murad commented on deploy.sh
> +git commit -m "Deploy docs"
Creating a TAG at `cadasta/cadasta-platform` and `cadasta/api-docs` at same time will makes sense. That way we can also corrosponde every version of cadasta-platform to its doc

2017-10-26 14:50 UTC, oliverroick commented on deploy.sh
> +git commit -m "Deploy docs"
> I'm suggesting updating the docs after every commit because after my PRs #37, #39, #36
The docs are still not updated to reflect the changes.

We simply forgot; I'll take care of the deployment tomorrow. Updating the docs after every commit is still not an option. 

> Once a TAG is created at cadasta/cadasta-platform i will right a script that will create the TAG in this repository as well.

That's something we can do further down the line. I'd say we focus on this PR first and then look at follow-ups.

2017-10-29 17:56 UTC, m-murad commented
@oliverroick 
Correct me if I'm wrong. 
What you want is that every time you create and push a `tag`, the `gh-pages` branch should be updated from the code thats in `master` branch?

2017-10-30 07:37 UTC, oliverroick commented
Yes that's correct

2017-10-30 12:28 UTC, m-murad commented
@oliverroick 
I have updated the PR.
The `gh-pages` branch will only be updated if a `TAG` is pushed to the repository.

The commit message will be of the format
"Docs updated for `TRAVIS_TAG`"
eg `Docs updated for v1.2`

2017-11-02 22:40 UTC, m-murad commented
I have fixed this. Please review


On Oct 30, 2017 1:07 PM, "Oliver Roick" <notifications@github.com> wrote:

> Yes that's correct
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Cadasta/api-docs/pull/44#issuecomment-340364933>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AQdmZNimzn6M4_VIDRaiJ_EaC_4bm2dTks5sxXyggaJpZM4P_-5Z>
> .
>

2017-11-03 08:08 UTC, oliverroick commented
It's on my list. I'll review when I get to it. It's not the highest priority at the moment

2022-08-10 21:49 UTC, closed without merging